				<div class="header">
					<div class="logo grid_5">
						<h1 title="MyBilling.cc is an easy and fast account software"><span>MyBilling.cc</span></h1>
					</div>
					<div class="user grid_11">
						<span>Welcome Thomas Stachl - <a href="" title="Manage your account settings">Account Settings</a> - <a href="<?php echo $this->baseUrl('login/logout') ?>" title="Logout from your MyBills.cc account">Logout</a></span>
					</div>
					<div class="clear"></div>
					<div class="title">
						<div class="grid_11 prefix_5">
							<h1><?php echo $this->title ?></h1>
						</div>
						<div class="clear"></div>
					</div>
				</div>