<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<?php echo $this->headMeta() ?>
		<?php echo $this->headTitle() ?>
		<?php echo $this->headLink() ?>
	</head>
	<body>
		<div id="wrapper" class="container_16">
			<?php echo $this->render('header.phtml') ?>
			<?php echo $this->layout()->sidebar ?>
			<?php #echo $this->partial('sidebar.phtml') ?>
			<div class="content grid_11">
				<?php echo $this->layout()->content ?>
			</div>
			<div class="clear"></div>
			<?php echo $this->render('footer.phtml') ?>
		</div>
		<?php echo $this->headScript() ?>
	</body>
</html>